# WorldEdit Forge WDG build identity
modDisplayName=WorldEdit-WDG
modBaseName=WorldEdit
jarBaseName=WorldEdit-Forge-WDG
modMainVersion=6
modSubVersion=1
modPatchVersion=2
modBuildNumber=3

# Legacy ForgeGradle builds are memory intensive on first setup.
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
